### PR TITLE
Changes to use Poly/ML with smackage

### PR DESCRIPTION
**Pull request by mclements**
The following commit allowed `smackage` to work with Poly/ML 5.7.1 Release on Ubuntu 16.04 LTS.

I do not know whether the call to `pkg-config` will be portable. 

I also tried using `configure.ac` to allow for the Poly/ML executable being called `polyml` or `poly` - but reverted those commits as the changes were too large.

Sincerely, Mark.

### CODE REVIEW

**Comment by mclements** [comment]
Would someone be able look at this pull request, please?

**Comment by gian** [comment]
@mclements Looks good! I'll merge this and push a release.

**Comment by mclements** [comment]
Thanks for following up on this. I also needed to symlink `poly` to `polml` on Ubuntu. I will ask the polyml mailing list about changing the default in the `Makefile` to `POLYML=poly`.

**Comment by mclements** [comment]
An alternative would be to assume GNU Make and:

POLYML := $(shell { command -v poly || echo polyml; } 2>/dev/null)

**Pull request merged**
